language: python

python:
  - 2.7
  - 3.4
  - 3.5

env:
  - DJANGO=Django<1.9
  - DJANGO=Django<1.10

matrix:
  allow_failures:
    # Allow failures for unreleased Django version
    - python: 3.4
    - python: 3.5

# command to install dependencies
install:
  - pip install -q $DJANGO --use-mirrors
  - pip install -r requirements.txt --use-mirrors
  - pip install -r requirements_test.txt --use-mirrors

# command to run tests
script: python runtests.py
