language: python

python:
  - 2.7

env:
  - DJANGO=Django<1.8
  - DJANGO=Django<1.9
  - DJANGO=Django==1.9rc1

# command to install dependencies
install:
  - pip install -q $DJANGO --use-mirrors
  - pip install -r requirements.txt --use-mirrors

# command to run tests
script: python setup.py test
